avtozip/avtozip/urls.py
"""avtozip URL Configuration."""

from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin

from httpproxy.views import HttpProxy

from webstore.api.urls import webstore_api

from . import views


urlpatterns = [
    url(r'^$', views.dashboard_view, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include(webstore_api.urls)),
    url(r'^webstore/', include('webstore.urls', namespace='webstore')),
    url(r'^rosetta/', include('rosetta.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^tecdoc/(?P<url>.*)$', HttpProxy.as_view(base_url=settings.PROXY_TECDOC_URL)),
]

avtozip/store/urls.py
"""Store application url configuration."""

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index_view, name='index'),
]

avtozip/templates/aside.html
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="#"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-bar-chart-o fa-fw"></i> Statistics<span class="fa arrow"></span></a>
                            <ul class="nav nav-second-level">
                                <li>
                                    <a href="#">Flot Charts</a>
                                </li>
                                <li>
                                    <a href="#">Morris.js Charts</a>
                                </li>
                            </ul>
                            <!-- /.nav-second-level -->
                        </li>
                    </ul>

avtozip/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  {% bootstrap_css %}
  {% block css %}{% endblock %}
  {% block js_header %}{% endblock %}
  {% bootstrap_javascript %}
</head>
<body>
  <header class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    {% block header %}{% endblock %}
    <nav>
      {% block nav %}{% endblock %}
    </nav>
    <aside class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        {% block aside %}{% endblock %}
      </div>
    </aside>
  </header>
  <main id="page-wrapper">
    {% block main %}{% endblock %}
  </main>
  <footer>
    {% block footer %}{% endblock %}
  </footer>
  {% block js_content %}{% endblock %}
</body>
</html>

avtozip/templates/footer.html
<div class="nabvar navbar-default navbar-static-bottom">
  <span class="navbar-brand">{% trans 'Footer placeholder' %}
</div>

avtozip/templates/header.html
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
    <span class="sr-only">Toggle navigation</span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>
  <img src="{% static 'images/logo-avtozip.jpg' %}"/>
</div>
<!-- /.navbar-header -->

avtozip/templates/index.html
{% extends "main.html" %}

{% block main %}
  <div class="col-lg-12">
    <h1 class="page-header">{% trans 'AvtoZip DashBoard placeholder' %}</h1>
  </div>
{% endblock %}

avtozip/templates/main.html
{% extends "base.html" %}

{% block title %}{% trans 'AvtoZip Dashboard' %}{% endblock %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}" />
  <link rel="stylesheet" type="text/css" href="{% static 'font-awesome/css/font-awesome.css' %}" />
{% endblock %}

{% block js_header %}
  <script type="text/javascript" src='{% static 'jquery/dist/jquery.min.js' %}'></script>
  <script type="text/javascript" src='{% static 'metisMenu/dist/metisMenu.min.js' %}'></script>
{% endblock %}

{% block js_content %}
  <script type="text/javascript" src='{% static 'js/common.js' %}'></script>
{% endblock %}

{% block header %}
  {% include "header.html" %}
{% endblock %}

{% block nav %}
  {% include "nav.html" %}
{% endblock %}

{% block aside %}
  {% include "aside.html" %}
{% endblock %}

{% block footer %}
  {% include "footer.html" %}
{% endblock %}

avtozip/templates/nav.html
<ul class="nav navbar-top-links navbar-right">
  <li><a href="{% url 'index' %}">{% trans 'Dashboard' %}</a></li>
  <li><a href="{% url 'webstore:index' %}">{% trans 'Store' %}</a></li>
  <li>
    <form action="{% url 'set_language' %}" method="post">
      {% csrf_token %}
      <input name="next" type="hidden" value="{{ redirect_to }}" />
      <select class="form-control" name="language" onchange="this.form.submit()">
        {% get_current_language as LANGUAGE_CODE %}
        {% get_available_languages as LANGUAGES %}
        {% get_language_info_list for LANGUAGES as languages %}
        {% for language in languages %}
          <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
            {{ language.name_local }} ({{ language.code }})
          </option>
        {% endfor %}
      </select>
    </form>
  </li>
  <li style="padding-right: 20px"></li>
</ul>